jobs:
  workflow:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Start uU
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./build/check

name: Main

on:
  schedule:
    - cron: "35 */1 * * *"
